---
spring: 
  profiles: 
    include: oauth
  jpa:
    show-sql: true
    properties:
      hibernates: 
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  h2: 
    console: 
      enabled: true
  datasource: 
    url: jdbc:h2:mem:testdb
  session: 
    store-type: jdbc
  
  # Test OAuth
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: test
            client-secret: test
            scope: profile, email
...

